import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './lib/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface': '#fbf9f4',
        'surface-bright': '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-variant': '#e4e2dd',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#434842',
        'on-background': '#1b1c19',
        'background': '#fbf9f4',
        'primary': '#516051',
        'primary-container': '#697969',
        'primary-fixed': '#d6e7d4',
        'primary-fixed-dim': '#bacbb8',
        'on-primary': '#ffffff',
        'on-primary-fixed': '#111f13',
        'on-primary-fixed-variant': '#3c4a3c',
        'inverse-primary': '#bacbb8',
        'secondary': '#835247',
        'secondary-container': '#fdbdae',
        'secondary-fixed': '#ffdad2',
        'secondary-fixed-dim': '#f7b7a9',
        'on-secondary': '#ffffff',
        'on-secondary-fixed': '#331109',
        'on-secondary-fixed-variant': '#673b31',
        'on-secondary-container': '#794a3f',
        'tertiary': '#7b5500',
        'tertiary-container': '#976d1b',
        'tertiary-fixed': '#ffdeab',
        'tertiary-fixed-dim': '#f2be65',
        'on-tertiary': '#ffffff',
        'on-tertiary-fixed': '#281900',
        'on-tertiary-fixed-variant': '#5f4100',
        'on-tertiary-container': '#fffbff',
        'outline': '#747872',
        'outline-variant': '#c4c8c0',
        'error': '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        'surface-tint': '#536253',
      },
      fontFamily: {
        headline: ['Newsreader', 'serif'],
        body: ['Manrope', 'sans-serif'],
        label: ['Manrope', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm: '0.125rem',
        md: '0.25rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
    },
  },
  plugins: [],
}

export default config
